SELECT * FROM clientes;
SELECT * FROM clientes WHERE estado = 'SP';
SELECT * FROM clientes WHERE renda_mensal > 15000;
SELECT COUNT(*) FROM clientes WHERE data_entrada LIKE '2023%';
SELECT * FROM contratos WHERE status  = 'ativo';
SELECT * FROM contratos WHERE  data_fim > '2024-01-31'; 
SELECT * FROM funcionarios WHERE salario_mensal > 12000;
SELECT * FROM faturas WHERE status = 'aberta' AND vencimento >= '2025-01-01';
SELECT * FROM pagamentos WHERE metodo = 'pix';
SELECT * FROM chamados WHERE prioridade = 'critica' AND status = 'aberto';
SELECT * FROM clientes WHERE nome LIKE '%Consultoria%';
SELECT * FROM contratos WHERE data_inicio LIKE '2023%';
SELECT * FROM clientes WHERE estado IN ('RJ', 'SP' ,'MG');
SELECT * FROM faturas WHERE valor_liquido > 500 OR valor_desconto != 0;
SELECT * FROM funcionarios WHERE cargo = 'Consultor' OR cargo  = 'Especialista';
SELECT * FROM chamados WHERE titulo LIKE 'Erro%'; 
SELECT * FROM clientes ORDER BY renda_mensal DESC LIMIT 10;
SELECT * FROM contratos ORDER BY data_inicio DESC LIMIT 5;
SELECT * FROM funcionarios ORDER BY salario_mensal ASC LIMIT 10;
SELECT * FROM faturas ORDER BY valor_bruto DESC LIMIT 20;
SELECT * FROM pagamentos ORDER BY data_pagamento DESC LIMIT 5;
